In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("datasets/Cleaned-Titanic.csv")
df

,Survived,Pclass,Name,Sex,Age,siblings-spouses,Parents-children,Fare,Embarked
0,False,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,7.2500,S
1,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,71.2833,C
2,True,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,7.9250,S
3,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,53.1000,S
4,False,3,"Allen, Mr. William Henry",male,35.000000,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
886,False,2,"Montvila, Rev. Juozas",male,27.000000,0,0,13.0000,S
887,True,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,30.0000,S
888,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,23.4500,S
889,True,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,30.0000,C
890,False,3,"Dooley, Mr. Patrick",male,32.000000,0,0,7.7500,Q

In [3]:
df.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'siblings-spouses',
       'Parents-children', 'Fare', 'Embarked'],
      dtype='object')

In [4]:
df.shape

(891, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Survived          891 non-null    bool
 1   Pclass            891 non-null    int64
 2   Name              891 non-null    object
 3   Sex               891 non-null    object
 4   Age               891 non-null    float64
 5   siblings-spouses  891 non-null    int64
 6   Parents-children  891 non-null    int64
 7   Fare              891 non-null    float64
 8   Embarked          891 non-null    object
dtypes: bool(1), float64(2), int64(3), object(3)
memory usage: 56.7+ KB

In [6]:
df.describe()

           Pclass         Age  siblings-spouses  Parents-children        Fare
count  891.000000  891.000000        891.000000        891.000000  891.000000
mean     2.308642   29.699118          0.523008          0.381594   32.204208
std      0.836071   13.002015          1.102743          0.806057   49.693429
min      1.000000    0.420000          0.000000          0.000000    0.000000
25%      2.000000   22.000000          0.000000          0.000000    7.910400
50%      3.000000   29.699118          0.000000          0.000000   14.454200
75%      3.000000   35.000000          1.000000          0.000000   31.000000
max      3.000000   80.000000          8.000000          6.000000  512.329200

In [7]:
df.isnull().sum()

Survived            0
Pclass              0
Name                0
Sex                 0
Age                 0
siblings-spouses    0
Parents-children    0
Fare                0
Embarked            0
dtype: int64

In [8]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [10]:
df.head()

,Survived,Pclass,Name,Sex,Age,siblings-spouses,Parents-children,Fare,Embarked
0,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,S
1,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C
2,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,S
3,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,S
4,False,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,S

In [11]:
df.tail()

,Survived,Pclass,Name,Sex,Age,siblings-spouses,Parents-children,Fare,Embarked
886,False,2,"Montvila, Rev. Juozas",male,27.000000,0,0,13.00,S
887,True,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,30.00,S
888,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,23.45,S
889,True,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,30.00,C
890,False,3,"Dooley, Mr. Patrick",male,32.000000,0,0,7.75,Q

In [12]:
df.dtypes

Survived               bool
Pclass                int64
Name                 object
Sex                  object
Age                 float64
siblings-spouses      int64
Parents-children      int64
Fare                float64
Embarked             object
dtype: object